#!/usr/bin/env bash
set -euo pipefail

#
# Commands
#

GO="${GO:-go}"

#
#
#

. scripts/library.sh

$GO generate ./hack/generate/generate.go

while IFS= read STEPDIR; do
  if [ -x "${STEPDIR}/scripts/generate" ]; then
    echo "# generate: ${STEPDIR}"
    ( cd "${STEPDIR}" && exec scripts/generate )
  fi
done < <( nebula::steps::step_dirs )
