#!/usr/bin/env bash
set -euo pipefail

. scripts/library.sh

DOCKER="${DOCKER:-docker}"

while IFS= read IMAGE; do
  echo "# release: ${IMAGE}"
  $DOCKER push $IMAGE
done < <( nebula::steps::step_images )
